### ISSUE TITLE
json改进建议

### ISSUE THREAD

**Issue by serverbread** [WhirlScript/hello#1]
是否在whirlpool.json中加入关于包的简单描述比较好
不然搞个描述还要去clone仓库读readme（）太低效了

**Comment by serverbread** [comment]
![2e089fe85fddee0733d2def19654e7da](https://github.com/WhirlScript/hello/assets/119761840/0cc6818d-7755-40ab-b154-484c494b92b7)
我这么创建个表如何？

**Comment by Bluemangoo** [comment]
> 是否在whirlpool.json中加入关于包的简单描述比较好 不然搞个描述还要去clone仓库读readme（）太低效了

包管理不需要知道描述，只是追踪id和仓库。需要知道描述要自行安装包再去读安装的包的readme，写IDE插件的时候会做readme渲染的。

**Comment by serverbread** [comment]
好好
